blank_issues_enabled: false
contact_links:
  - name: 🐧 Miracles Journey 整合包官方QQ群
    url: https://qm.qq.com/q/LztDsb7qg4
    about: 记得要加群啊! 一定要加啊!

  - name: 📜 Miracles Journey Wiki
    url: https://miraclesjourney.qianf.fun/
    about: 官方Wiki, 有一些教程和常见问题解答
