
["Client Configs"]
	#if, false then the Enderite Items have no tooltip. Default is true
	EnderiteItemTooltips = true
	#If, false then the Enderite Chestplate Elytra use the normal Elytra texture without the Cape texture. Default is true
	EnderiteElytraChestplateUseCapeTexture = true
	#If, false then the Enderite Chestplate Elytra use the Vanilla Elytra Texture. Default is true
	EnderiteElytraChestplateUseCustomTexture = true

	["Client Configs"."Enderite Sword"]
		#If false, then you do not have the Info, that you need to charge it with Ender Pearls for Teleport. If 'EnderiteItemTooltips' is false, then this is also gone. Default is true.
		EnderiteSwordChargesInfo = true

