
[information_format]
	#The display mode for any Reveal coordinates upgrades.
	#1 - XYZ: X.XXX / Y.YYYYY / Z.ZZZ
	#2 - XYZ: X.XXX, Y.YYYYY, Z.ZZZ
	#3 - X.XXX / Y.YYYYY / Z.ZZZ
	#4 - X.XXX, Y.YYYYY, Z.ZZZ
	#[Default: 1]
	#Range: 1 ~ 4
	coordinateDisplayMode = 1
	#The display mode for any Reveal time upgrades.
	#1 - Day #, HH:MM AM/PM
	#2 - Day #, HH:MM
	#3 - HH:MM AM/PM
	#4 - HH:MM
	#[Default: 1]
	#Range: 1 ~ 4
	timeDisplayMode = 1

