
[tooltip]
	#Does the upgrade tooltip require a key to be held to expand?
	#[Default: true]
	requiresKeyHeld = true
	#Show an item's upgrade id when advanced tooltips are enabled
	#[Default: false]
	showUpgradeID = false
	#Uses roman numerals instead of numbers when describing enchantments.
	#[Default: false]
	useRomanNumerals = false

[jei]

	#Tweaking the area you can click in the smithing table gui to view upgrade recipes.
	#Mainly intended if you have an incompatible gui modifying resource pack.
	#>> Requires a reload for changes to apply! <<
	[jei.recipeClickArea]
		#X of left edge of click area
		#[Default (Hammer): 17]
		#[Alternative (Plus Icon): 53]
		#Range: 0 ~ 175
		recipeClickAreaLeftX = 17
		#Y of top edge of click area
		#[Default (Hammer): 7]
		#[Alternative (Plus Icon): 49]
		#Range: 0 ~ 165
		recipeClickAreaTopY = 7
		#Width of click area
		#[Default (Hammer): 30]
		#[Alternative (Plus Icon): 13]
		#Range: 1 ~ 176
		recipeClickAreaWidth = 30
		#Height of click area
		#[Default (Hammer): 30]
		#[Alternative (Plus Icon): 13]
		#Range: 1 ~ 166
		recipeClickAreaHeight = 30

[decoration]
	#Should the mod render upgrade overlays on items in a GUI?
	#This texture is an overlay, and will not recieve effects like enchantment glow.
	#NOTE: This does NOT disable the loading of the textures, just the rendering
	#[Default: true]
	renderUpgradeOverlays = true
	#Determines what depth the overlay renders at, allowing fine tuning of which elements the overlay appears above and below.
	#Don't touch unless the overlay is appearing over things besides the item and its' enchantment glow.
	#>> Requires a resource pack reload in order to take effect!
	#[Default: 110]
	#Range: 0 ~ 500
	overlayRenderDepth = 110

