
[logbegone]
phrases = [
    "Mixin config",
    "Disconnecting VANILLA connection attempt",
    "was empty after loading",
    "does not exist in classpath",
    "is using deprecated binbBlockRenderLayers option",
    "Failed to load plugin",
    "Failed to fetch dev cape data",
    "Some mod loaded the Sheets class to early!",
    "Calling client config when it is not yet available",
    "Failed to generate record item texture",
    "Using missing texture, unable to load",
    "Could not load contributor+special revolver list",
    "Failed to load patreon information",
    "Adding duplicate key",
    "Exception loading patreon",
    "Key mapping key.ingameime.hotkey registered after event",
    "Remote host terminated the handshake",
    "raw.githubusercontent.com",
    "Error loading plugin at com.jaquadro.minecraft.storagedrawers.integration.Waila",
    "Couldn't locate icons for flat:",
    "Unable to parse language metadata section of resourcepack",
    "Failed to get filter section from pack",
    "Couldn't load certain entries with the tag",
    "Could not read Refined Storage resource pack section",
    "Couldn't parse data file",
    "Parsing error loading recipe",
    "Couldn't parse loot table",
    "Some mods (see below stack trace) have errors which will prevent Supplementaries from working correctly.Continuing",
    "Exception caught when registering",
    "Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder",
    "Caught an error from mod plugin",
    "Exception caught during firing event",
    "Failed to get tooltip",
    "An error occurred building event handler",
    "Deleting stream buffers: Invalid operation",
]
regex = []
