
["充能强化"]
	#充能强化 特性使用的物品, 默认: "minecraft:bedrock"
	"使用的物品" = "minecraft:bedrock"
	#充能强化 特性攻击增益, 0.1代表10%额外伤害, 默认: 0.1
	#Range: 0.0 ~ 10.0
	"增益" = 0.1

["远射"]
	#远射 特性伤害系数, 1.0代表最终伤害*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"系数" = 1.0

["高地"]
	#高地 特性伤害系数, 1.0代表最终伤害*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"系数" = 1.0

["冲击"]
	#冲击 特性水平击退系数, 1.0代表最终水平击退力度*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"水平系数" = 1.0
	#冲击 特性垂直击退系数, 1.0代表最终垂直击退力度*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"垂直系数" = 1.0

["饱和"]
	#饱和 特性攻击增益, 0.2代表20%额外伤害, 默认: 0.2
	#Range: 0.0 ~ 10.0
	"增益" = 0.2
	#饱和 特性血量百分比阈值, 0.8代表80%血量以上, 默认: 0.8
	#Range: 0.0 ~ 1.0
	"阈值" = 0.8

["破釜沉舟"]
	#破釜沉舟 特性攻击增益, 0.2代表20%额外伤害, 默认: 0.2
	#Range: 0.0 ~ 10.0
	"增益" = 0.2
	#破釜沉舟 特性血量百分比阈值, 0.3代表代表30%血量以下, 默认: 0.3
	#Range: 0.0 ~ 1.0
	"阈值" = 0.3

["连击"]
	#连击 特性攻击增益, 0.03代表每段3%额外伤害, 默认: 0.03
	#Range: 0.0 ~ 1.0
	"增益" = 0.03
	#连击 特性攻击段数, 5代表最高五段, 默认: 5
	#Range: 1 ~ 100
	"段数" = 5
	#连击 特性是否因为受伤清零, true代表中止, 默认: true
	"是/否" = true

["同调"]
	#同调 特性生效的物品, 默认: "minecraft:barrier"
	"生效的物品" = "minecraft:barrier"
	#同调 特性修补收益, 0.025代表每个物品每秒修复0.025耐久值, 默认: 0.025
	#Range: 0.0 ~ 1.0
	"增益" = 0.025
	#同调 特性生效物品数量上限, 64代表最高64个物品, 默认: 64
	#Range: 1 ~ 100
	"数量" = 64

["荣耀"]
	#荣耀 特性给予村庄英雄的时长, 单位为分钟, 默认: 30
	#Range: 1 ~ 60
	"时长" = 30
	#荣耀 特性给予村庄英雄时消耗的耐久, 默认: 100
	#Range: 0 ~ 1000
	"消耗耐久" = 100
	#荣耀 特性给予村庄英雄的上限等级, 默认: 5
	#Range: 1 ~ 255
	"等级" = 5
	#荣耀 特性是否逐级提升至最高等级, 若为否则一次性给予最高等级, 默认: 是
	"是/否" = true

["邪念"]
	#邪念 特性给予不祥之兆的时长, 单位为分钟, 默认: 5
	#Range: 1 ~ 60
	"时长" = 5
	#邪念 特性给予不祥之兆时消耗的耐久, 默认: 100
	#Range: 0 ~ 1000
	"消耗耐久" = 100
	#邪念 特性给予不祥之兆的上限等级, 默认: 5
	#Range: 1 ~ 255
	"等级" = 5
	#邪念 特性是否逐级提升至最高等级, 若为否则一次性给予最高等级, 默认: 是
	"是/否" = true

